### ISSUE TITLE
Create mockup for the Credit underwriter

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#121]

**Comment by Harinag12** [comment]
In the credit underwriter screen, I've covered statistics of "loan applications ready for approval, approved, and rejected. 
Table view: covered the list of loan applications based on KPI interaction and the ability to change the LMS calculated interest rate.

https://xd.adobe.com/view/92a12046-379d-46b0-a0df-0261cdf94472-c7f2/

**Comment by leelakrishna-t** [comment]
[LMS-Credit underwriter.pdf](https://github.com/user-attachments/files/17410803/LMS-Credit.underwriter.pdf)
