### ISSUE TITLE
Copy changes to the Loan Manager dashboard

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#159]

**Comment by leelakrishna-t** [comment]
1. "My active loans" to "My active applications"
2. "Overdue Loans" to "Payment overdue applications"
3. "Rejected loans" to "Rejected applications"

**Comment by AnuragServacuity** [comment]
Done. Merge in  dev server

**Comment by AnuragServacuity** [comment]
https://github.com/ServAcuity/lms-frontend/pull/16

changes in the above PR
