### ISSUE TITLE
Not able to change assigned loan manager and credit underwriter

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#160]
Not able to change assigned loan manager and credit underwriter,
not able to assign other  loan manager and credit underwriter,

**Comment by tejasbizacuity** [comment]
![Image](https://github.com/user-attachments/assets/beee75d4-11c0-4427-8acb-cf1ab7ebf7bc)

**Comment by SA-Kiran** [comment]
pr 6
