### ISSUE TITLE
Rejected application should not get process anymore

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#166]

**Comment by leelakrishna-t** [comment]
1. Loan application rejected due to no suitable model in the DE

2. incorrect status for the rejected loan
![Image](https://github.com/user-attachments/assets/04271a07-be43-4633-9b35-afcc9d341fdd)

3. Again able to hit the DE
![Image](https://github.com/user-attachments/assets/9d27f56a-9223-43df-930e-43590df944bc)

If the loan application rejected for any reason, it should not get processed again.

**Comment by leelakrishna-t** [comment]
4. We should not display the rejected applications in the LM dashboard

**Comment by AnuragServacuity** [comment]
https://github.com/ServAcuity/lms-frontend/pull/19
