### ISSUE TITLE
Remove Action in to the Loan Manager

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#180]

**Comment by leelakrishna-t** [comment]
for LM, individual stages of a each loan 
![Image](https://github.com/user-attachments/assets/55e45764-4aa7-4361-91fe-24b280d8e087)
![Image](https://github.com/user-attachments/assets/63c14802-435a-4faf-b08f-1984957eb4e7)
![Image](https://github.com/user-attachments/assets/5eb4ef12-066d-4618-963e-04fa54c65727)
Remove "Action" column completely

**Comment by leelakrishna-t** [comment]
![Image](https://github.com/user-attachments/assets/c8671e60-6d3d-4826-8fcd-9ff287026ae7)

**Comment by AnuragServacuity** [comment]
completed in the PR 17
