### ISSUE TITLE
UI issues on loan manager dashboard

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#182]
![Image](https://github.com/user-attachments/assets/d462b598-3a41-4522-88ba-c2c560850f95)

**Comment by AnuragServacuity** [comment]
https://github.com/ServAcuity/lms-frontend/pull/24

added in above PR

**Comment by AnuragServacuity** [comment]
![Image](https://github.com/user-attachments/assets/583448d1-53e1-4e28-954c-617b315fe298)


To maintain responsive design of the KPI cards, this is the best alignment we can do.
