### ISSUE TITLE
API is failing , saying "No suitable model found for given loan" , after entering values as shown in screenshot

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#184]
![Image](https://github.com/user-attachments/assets/ebe8b71a-7211-4fbd-a545-72b704333b0b)

**Comment by Akhilkonduru96** [comment]
Solved. PR#18

**Comment by tejasbizacuity** [comment]
still able to reproduce

**Comment by tejasbizacuity** [comment]
still able to reproduce

**Comment by tejasbizacuity** [comment]
Still able to reproduce , please add in sprint 17
