### ISSUE TITLE
Get interest rate button should be disabled after calculating interest rate on IRC screen

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#186]
![Image](https://github.com/user-attachments/assets/dd1f76e2-5e1e-4195-9202-0d58feb48fdb)
**_No use of that button after calculating interest rate._**_

**Comment by AnuragServacuity** [comment]
https://github.com/ServAcuity/lms-frontend/pull/24

added in the above PR
