### ISSUE TITLE
Enhancement: Add back/Go to dashboard button on AML checks , risk rating , IRCR, FetchPaymentSchedule, FacilityLetter ,Checklist screen

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#187]
![Image](https://github.com/user-attachments/assets/4841692e-de93-4c80-8613-e7c860f38aed)

**Comment by AnuragServacuity** [comment]
Instead of back button on each page, the user can go back to dashboard by clicking on ServAcuity icon in the header. (discussion with Hari and Leela).
