### ISSUE TITLE
Notification to the portal user after disbursement of the loan

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#218]

**Comment by SA-Kiran** [comment]
portal-backend PR number 19

**Comment by tejasbizacuity** [comment]
unable to test due to facility letter issue.

**Comment by tejasbizacuity** [comment]
![image](https://github.com/user-attachments/assets/d4add2ab-38f7-4426-a459-634ac68c6679)
Unable to click on next button , unable to disburse the loan
