### ISSUE TITLE
Signed facility letter , but still not able to click on "Next" button on smart checklist screen.

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#226]
![Image](https://github.com/user-attachments/assets/c425e091-45e7-4f66-ad3f-195db83d1bfd)

**Comment by Akhilkonduru96** [comment]
Raised PR#29
https://github.com/ServAcuity/lms-backend/pull/29

**Comment by Akhilkonduru96** [comment]
raised PR#30
