### ISSUE TITLE
Typo in email sent to loan manager (interest rate finalized email)

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#227]
![Image](https://github.com/user-attachments/assets/5de8701e-9a0b-4a1e-9dfb-2760eb24c8e6)

**Comment by Akhilkonduru96** [comment]
![Image](https://github.com/user-attachments/assets/89285098-346d-4512-84a9-aefbea8d7d84)
this is fixed.

**Comment by tejasbizacuity** [comment]
Looking as expected , closing this issue.
