### ISSUE TITLE
Identify the data to populate risk rating screen from Experian Data.

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#230]

**Comment by Akhilkonduru96** [comment]
link :- https://developer.experian.com/products/uk/commercial-credit/commercial-credit-api-docs#

API:_-get /v2/registeredcompanycredit/{RegNumber}

details that can be found:- net worth, turnover, dividends, profit loss, profit loss previous, gross profit, net profit etc.
