### ISSUE TITLE
Able to enter data twice on IRCR screen , also incorrect message in background.

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#241]
on IRCR screen , 
1.Entered arrangement fee
2.Clicked on calculate
3.Clicked on froward to credit underwriter.
4.GO to dashboard
5.Click on Interest rate calculation icon ,

6.Repeat same procedure as above

able to enter data twice.

also incorrect message in background.

![Image](https://github.com/user-attachments/assets/c4eddde2-3cc8-4977-929d-c703456e50fa)

**Comment by AnuragServacuity** [comment]
https://github.com/ServAcuity/lms-frontend/pull/27

added in above PR

**Comment by tejasbizacuity** [comment]
**Repeated same procedure as above,
that "Continue application" pop up coming , and after that user directed to dahboard .Again if i tried to repeat same procedure , then "Wait for Creditunderwriter for its decision" pop up coming.
not able to enter data twice.
Partially fixed , closing this issue.**
