### ISSUE TITLE
Pop up coming, (1. fetch payment schedule and click on next button,   2.before signing facility letter)

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#243]
![Image](https://github.com/user-attachments/assets/1d793e5f-8056-4612-9930-17ba88c5172c)
![Image](https://github.com/user-attachments/assets/632daada-aa95-4e96-bdb1-e1bf6ea66a39)

**Comment by AnuragServacuity** [comment]
https://github.com/ServAcuity/lms-frontend/pull/27

added in this PR

**Comment by tejasbizacuity** [comment]
working as expected , closing this issue.
