### ISSUE TITLE
Loan disbursement mail received , but notification not sent to portal user. Also any other notification were not present. Also incorrect text in "Loan disbursed" mail.

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#252]
![Image](https://github.com/user-attachments/assets/bbf4b9a5-12c7-47b6-a09c-e16c3fb519d2)
<img width="839" alt="Image" src="https://github.com/user-attachments/assets/44d0147a-93d8-46fb-b086-57db49749fca" />

**_Also incorrect text in "Loan disbursed" mail.
As we are taking bank details on smart checklist screen , here it is asking to complete bank details via mail , after disbursement of loan .Modify the text in mail as per process._**

**Comment by SA-Kiran** [comment]
PR number 34

**Comment by tejasbizacuity** [comment]
working as expected , closing this bug.
