### ISSUE TITLE
Draft the facility letter for the signing

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#50]
Loan manager to prepare a Facility letter and send it to the applicant for his final approval

**Comment by kiranbedib** [comment]
[Uploading Appendix A - Draft Template Loan Agreement.pdf…]()
This is the reference for facility letter

**Comment by Akhilkonduru96** [comment]
Pr number 16, start date: 7 nov 2024 ,end date : 20 nov 2024
