### ISSUE TITLE
Demographic report: Create synthesize data and generate the report

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#61]

**Comment by naveen-biz** [comment]
Demogrpahics Report Snapshot:
![Image](https://github.com/user-attachments/assets/10b075ec-1c1c-4719-8f1d-e61470f19bef)
![Image](https://github.com/user-attachments/assets/3386f780-1354-4076-a5f3-767b63f7f531)
![Image](https://github.com/user-attachments/assets/68856893-a3e3-478e-94f9-0caa3adcd021)
![Image](https://github.com/user-attachments/assets/75ada8a1-15d7-4a62-9984-5f989cdb6204)
![Image](https://github.com/user-attachments/assets/18d6f84b-d1e2-422d-9a91-399c8ab21be1)
![Image](https://github.com/user-attachments/assets/735531fc-d209-4f29-9492-6dc5f5478162)
