### ISSUE TITLE
Enhancement : Add a content and description page to each report, with easy navigation from the first page.

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#90]

**Comment by naveen-biz** [comment]
I've prepared two templates for the homepage. In the first template, the description is displayed **directly on the tab**, while the second template is designed for cases with **multiple tabs**, where the description appears in a tooltip. Both templates feature fully clickable buttons that redirect to the relevant pages. Additionally, I’ve incorporated a darker background, similar to the Eligibility Criteria page in the LOS application, for one version.

After a call with Adi, we decided on a side-by-side layout for the report name and description. I'll be adding a **QA button, breadcrumbs for navigation, and a description button**, and I'm currently working on the feedback

**Comment by naveen-biz** [comment]
We went with a side-by-side layout for the report name and description. I’ve prepared and published it to the production workspace. The report offers two templates—one using breadcrumbs for navigation and the other with a feature that lets you return to the homepage by clicking on the brand logo.
