### ISSUE TITLE
Migrate all existing XD mockups to Figma

### ISSUE THREAD

**Issue by leelakrishna-t** [ServAcuity/ServAcuity#98]

**Comment by leelakrishna-t** [comment]
Adobe XD is giving up on its Figma alternative.

https://timesofindia.indiatimes.com/gadgets-news/adobe-is-reportedly-giving-up-on-its-figma-alternative/articleshow/107327121.cms

![Image](https://github.com/user-attachments/assets/8f3f5a52-159b-4b0e-93d4-6e4a6db38a5a)

**Comment by Harinag12** [comment]
Hi leela,
In accordance with our conversation, I have converted RB XD files to Figma format. We are now ready to switch to Figma.

**Comment by Harinag12** [comment]
These are the figma-formatted rb files.  

https://rgcloudltd.sharepoint.com/:u:/s/ServAcuity-RBL-Documentation/Ee31CH0BS_ZBgxeV7QO2xTQBmKwOUhtqvM3p7qA7zHq9HQ?e=8pum4T
